name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: pip install kivy
        run: pip install kivy
      - name: pip install google
        run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
      - name: download libs
        run:
          make  
